apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-api-service
  labels:
    app: k8s-demo-api
spec:
  selector:
    app: k8s-demo-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
